name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set version from tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Setting version to $VERSION"
        mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

    - name: Build and test
      run: mvn clean verify

    - name: Build sources and javadoc
      run: |
        mvn source:jar
        mvn javadoc:jar

    - name: Publish to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}